#!/bin/sh

# clear rules
bspc rule -r "*"

### AUTOSTART ###
pgrep -x sxhkd > /dev/null 2>&1 || sxhkd &
pgrep -x flameshot > /dev/null 2>&1 || flameshot &
pgrep -x spotify-listene > /dev/null 2>&1 ||spotify-listener &                      # polybar spotify module dbus event listener
pgrep bspswallow > /dev/null 2>&1 || bspswallow &
launchpolybar &

### MONITORS ###
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

#### BSPWM configuration ####
#bspc config border_radius                8
bspc config border_width                  2
bspc config window_gap                    0
bspc config top_padding                   21
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                none
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
# bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
# bspc config automatic_scheme              longest_side
bspc config initial_polarity              second_child 

bspc config pointer_modifier mod1
bspc config pointer_action1 resize_corner
bspc config pointer_action2 resize_side
bspc config pointer_action3 move

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

# fix discord startup stealing focus
bspc config ignore_ewmh_focus true

#### BSPWM coloring ####
#bspc config normal_border_color		      "#4c566a"
#bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
#bspc config urgent_border_color 	      "#dd2727"

#### Rules #####
# second classnames
bspc rule -a Spotify desktop=^9
bspc rule -a discord desktop=^10
bspc rule -a alacritty-social desktop=^10
bspc rule -a TelegramDesktop desktop=^10
bspc rule -a firefox desktop=^2
bspc rule -a feh state=floating
bspc rule -a floating-term state=floating rectangle=946x558+478+258
# bspc rule -a drop-down-term state=floating rectangle=1912x350+2+23 hidden=on sticky=on locked=on
bspc rule -a scratchpad-terminal sticky=on state=floating hidden=on
bspc rule -a Pulseaudio-equalizer-gtk state=floating
bspc rule -a Zathura state=tiled split_ratio=0.6

# Initialise drop-down terminal and ~/bin/bspscratchpad
bspdropterm --init
